package cn.mmsq.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTalk<M extends BaseTalk<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setPics(java.lang.String pics) {
		set("pics", pics);
		return (M)this;
	}

	public java.lang.String getPics() {
		return getStr("pics");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public M setUid(java.lang.String uid) {
		set("uid", uid);
		return (M)this;
	}

	public java.lang.String getUid() {
		return getStr("uid");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setUname(java.lang.String uname) {
		set("uname", uname);
		return (M)this;
	}

	public java.lang.String getUname() {
		return getStr("uname");
	}

	public M setState(java.lang.String state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.String getState() {
		return getStr("state");
	}

}
