package cn.mmsq.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGwc<M extends BaseGwc<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setUid(java.lang.String uid) {
		set("uid", uid);
		return (M)this;
	}

	public java.lang.String getUid() {
		return getStr("uid");
	}

	public M setPid(java.lang.String pid) {
		set("pid", pid);
		return (M)this;
	}

	public java.lang.String getPid() {
		return getStr("pid");
	}

	public M setCount(java.lang.String count) {
		set("count", count);
		return (M)this;
	}

	public java.lang.String getCount() {
		return getStr("count");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}

	public java.util.Date getTime() {
		return get("time");
	}

}
