package cn.mmsq.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return getStr("username");
	}

	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}

	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	public M setPass(java.lang.String pass) {
		set("pass", pass);
		return (M)this;
	}

	public java.lang.String getPass() {
		return getStr("pass");
	}

	public M setHead(java.lang.String head) {
		set("head", head);
		return (M)this;
	}

	public java.lang.String getHead() {
		return getStr("head");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}

	public java.lang.String getTel() {
		return getStr("tel");
	}

	public M setXx(java.lang.String xx) {
		set("xx", xx);
		return (M)this;
	}

	public java.lang.String getXx() {
		return getStr("xx");
	}

	public M setZy(java.lang.String zy) {
		set("zy", zy);
		return (M)this;
	}

	public java.lang.String getZy() {
		return getStr("zy");
	}

	public M setBj(java.lang.String bj) {
		set("bj", bj);
		return (M)this;
	}

	public java.lang.String getBj() {
		return getStr("bj");
	}

	public M setXb(java.lang.String xb) {
		set("xb", xb);
		return (M)this;
	}

	public java.lang.String getXb() {
		return getStr("xb");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public M setShdz(java.lang.String shdz) {
		set("shdz", shdz);
		return (M)this;
	}

	public java.lang.String getShdz() {
		return getStr("shdz");
	}

}
