package cn.mmsq.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import java.lang.String;
import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDic<M extends BaseDic<M>> extends Model<M> implements IBean {

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}

	public String getId() {
		return getStr("id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setType(String type) {
		set("type", type);
		return (M)this;
	}

	public String getType() {
		return getStr("type");
	}

	public M setTime(Date time) {
		set("time", time);
		return (M)this;
	}

	public Date getTime() {
		return get("time");
	}

}
