package cn.mmsq.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setPid(java.lang.String pid) {
		set("pid", pid);
		return (M)this;
	}

	public java.lang.String getPid() {
		return getStr("pid");
	}

	public M setPname(java.lang.String pname) {
		set("pname", pname);
		return (M)this;
	}

	public java.lang.String getPname() {
		return getStr("pname");
	}

	public M setCount(java.lang.String count) {
		set("count", count);
		return (M)this;
	}

	public java.lang.String getCount() {
		return getStr("count");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}

	public java.lang.String getTel() {
		return getStr("tel");
	}

	public M setSjr(java.lang.String sjr) {
		set("sjr", sjr);
		return (M)this;
	}

	public java.lang.String getSjr() {
		return getStr("sjr");
	}

	public M setUid(java.lang.String uid) {
		set("uid", uid);
		return (M)this;
	}

	public java.lang.String getUid() {
		return getStr("uid");
	}

}
