package cn.mmsq.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPics(java.lang.String pics) {
		set("pics", pics);
		return (M)this;
	}

	public java.lang.String getPics() {
		return getStr("pics");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public M setZz(java.lang.String zz) {
		set("zz", zz);
		return (M)this;
	}

	public java.lang.String getZz() {
		return getStr("zz");
	}

	public M setCbs(java.lang.String cbs) {
		set("cbs", cbs);
		return (M)this;
	}

	public java.lang.String getCbs() {
		return getStr("cbs");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return getStr("type");
	}

	public M setTj(java.lang.String tj) {
		set("tj", tj);
		return (M)this;
	}

	public java.lang.String getTj() {
		return getStr("tj");
	}

	public M setFj(java.lang.String fj) {
		set("fj", fj);
		return (M)this;
	}

	public java.lang.String getFj() {
		return getStr("fj");
	}

	public M setState(java.lang.String state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.String getState() {
		return getStr("state");
	}

}
