package cn.mmsq.entity;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tb_dic", "id", Dic.class);
		arp.addMapping("tb_manager", "id", Manager.class);
		arp.addMapping("tb_pl", "id", Pl.class);
		arp.addMapping("tb_product", "id", Product.class);
		arp.addMapping("tb_sc", "id", Sc.class);
		arp.addMapping("tb_user", "id", User.class);
	}
}

