package cn.mmsq.entity;

import cn.mmsq.entity.base.BaseDic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dic extends BaseDic<Dic> {
	public static final Dic dao = new Dic().dao();
}
