package cn.mmsq.entity;

import cn.mmsq.entity.base.BaseGg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Gg extends BaseGg<Gg> {
	public static final Gg dao = new Gg().dao();
}
