package cn.mmsq.entity;

import cn.mmsq.entity.base.BaseGwc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Gwc extends BaseGwc<Gwc> {
	public static final Gwc dao = new Gwc().dao();
}
