package cn.mmsq.entity;

import cn.mmsq.entity.base.BaseHg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Hg extends BaseHg<Hg> {
	public static final Hg dao = new Hg().dao();
}
