package cn.mmsq.entity;

import cn.mmsq.entity.base.BaseManager;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Manager extends BaseManager<Manager> {
	public static final Manager dao = new Manager().dao();
}
