package cn.mmsq.entity;

import cn.mmsq.entity.base.BaseNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class News extends BaseNews<News> {
	public static final News dao = new News().dao();
}
