package cn.mmsq.entity;

import cn.mmsq.entity.base.BasePl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Pl extends BasePl<Pl> {
	public static final Pl dao = new Pl().dao();
}
