package cn.mmsq.entity;

import cn.mmsq.entity.base.BaseSc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sc extends BaseSc<Sc> {
	public static final Sc dao = new Sc().dao();
}
