package cn.mmsq.entity;

import cn.mmsq.entity.base.BaseTalk;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Talk extends BaseTalk<Talk> {
	public static final Talk dao = new Talk().dao();
}
