package cn.mmsq.entity;

import cn.mmsq.entity.base.BaseXx;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Xx extends BaseXx<Xx> {
	public static final Xx dao = new Xx().dao();
}
