package cn.mmsq.entity;

import cn.mmsq.entity.base.BaseZan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Zan extends BaseZan<Zan> {
	public static final Zan dao = new Zan().dao();
}
